name: CI
on:
  push:
  schedule:
    - cron: '0 0 * * 0' # every Sunday at midnight to avoid token expiry
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Use Node.js 16.15.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Run tests
        run: pnpm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Use Node.js 16.15.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run lint
        run: pnpm run lint
  deploy:
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Use Node.js 16.15.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Authenticate Clasp
        run: 'echo "$CLASPRC" > ~/.clasprc.json'
        shell: bash
        env:
          CLASPRC: ${{ secrets.CLASPRC }}
      - name: Build
        run: pnpm run build
      - name: Deploy
        run: pnpm run deploy
